### ISSUE TITLE
Output Data Format

### ISSUE THREAD

**Issue by CraigMiloRogers** [usc-isi-i2/dig-crf#4]
The output, which is intended for consumption by Karma, should be a keyed JSON line.  The key should be the URI from the input (also a keyed JSON line).  The content should be a map of attribute types to attribute value sequences:

<key>\t{attrType1:` [values...], attrType2:[values]...}

attrType is one of "eyeColor" or "hairType".  Other attribute types may be defined in future CRF++ templates (e.g., skinColor), and it should not be necessary to make changes to the CRF++ processing to support them.

The attribute values are a sequence to allow for multi-token detections and/or multiple detections, e.g., multiple eye or hair colors.

**Comment by CraigMiloRogers** [comment]
Need further clarification on the value sequences.  Currently, CRF processing will produce a sequence of words, such as:

strawberry hairType
blond hairType
hair hairType

for a single detection.  Two hair color sequences would be detected as:

strawberry hairType
blond hairType
hair hairType
...
brown hairType
hair hairType

Does Karma want these two sequences concatenated together? e.g.:

hairType: ["strawberry", "blonde", "hair", "brown", "hair"]

**Comment by CraigMiloRogers** [comment]
In the future, the output data format might be enhanced to carry the position (token index) in the input data at which the annotated data was detected.

**Comment by CraigMiloRogers** [comment]
What if no attributes are detected by CRF++?  The most straightforward approach is to present an empty attribute map, but it would not be hard to suppress records with not attributes, if Karma would prefer that.

**Comment by szeke** [comment]
If no output is extracted simply don't generate an output record

**Comment by CraigMiloRogers** [comment]
Should the key be a quoted string ("uri") or should it be a bareword (uri)?  The quoted form is closer to the "jq" command's capabilities, but I had to step to step outside "jq" to generated keyed JSON Lines files, so I can do it either  way.

**Comment by CraigMiloRogers** [comment]
Here's what the output currently looks like (first line):

```
http://dig.isi.edu/sentence/253D8FF7A55A226FDBBC53939DBB90D763E77691    {"eyeColor": ["blue", "eyes"], "hairType": ["strawberry", "blond", "hair"]}
```

Here's the full sample:

[adjudicated_modeled_live_eyehair_100_03-tags.kjsonl.zip](https://github.com/usc-isi-i2/dig-crf/files/190321/adjudicated_modeled_live_eyehair_100_03-tags.kjsonl.zip)

**Comment by szeke** [comment]
We need to support extraction of multiple eye/hair colors from the same original text. There are many ways to do this. One possibility is:

```
{
  "eyeColor": [
    "blue eyes",
    "hazel"
  ],
  "hairType": [
    "strawberry blond hair",
    "long black hair"
  ]
}
```

Alternatively, could use multiple lines, one for each output, replicating the URI:

```
http://dig.isi.edu/sentence/253D8FF7A55A226FDBBC53939DBB90D763E77691 {"eyeColor": ["blue", "eyes"]}
http://dig.isi.edu/sentence/253D8FF7A55A226FDBBC53939DBB90D763E77691 {"hairType": ["strawberry", "blond", "hair"]}
http://dig.isi.edu/sentence/253D8FF7A55A226FDBBC53939DBB90D763E77691 {"eyeColor": ["hazel"]}
http://dig.isi.edu/sentence/253D8FF7A55A226FDBBC53939DBB90D763E77691 {"hairType": ["long", "black", "hair"]}
```

At the next level of processing we are likely to do word ngrams, which is going to want tokens again, so the second alternative may be better.

**Comment by CraigMiloRogers** [comment]
OK, entries are consecutive tags of the same type.

**Comment by CraigMiloRogers** [comment]
Here's new output.  A few lines:

```
http://dig.isi.edu/sentence/253D8FF7A55A226FDBBC53939DBB90D763E77691    {"hairType": ["strawberry", "blond", "hair"]}
http://dig.isi.edu/sentence/253D8FF7A55A226FDBBC53939DBB90D763E77691    {"eyeColor": ["blue", "eyes"]}
http://dig.isi.edu/sentence/028269F87330E727ACE0A8A39855325C5DD60FF8    {"hairType": ["long", "blonde", "hair"]}
http://dig.isi.edu/sentence/028269F87330E727ACE0A8A39855325C5DD60FF8    {"eyeColor": ["seductive", "blue", "eyes"]}
http://dig.isi.edu/sentence/028269F87330E727ACE0A8A39855325C5DD60FF8    {"hairType": ["blond", "hair"]}
http://dig.isi.edu/sentence/028269F87330E727ACE0A8A39855325C5DD60FF8    {"eyeColor": ["green", "eyes"]}
```

Here's the full sample:
[adjudicated_modeled_live_eyehair_100_03-tags.kjsonl.zip](https://github.com/usc-isi-i2/dig-crf/files/190334/adjudicated_modeled_live_eyehair_100_03-tags.kjsonl.zip)

**Comment by szeke** [comment]
Looks good
